export const API_ENDPOINTS = {
  HOME: '/home',
  SERVICE_CATEGORIES: '/service-categories',
  SERVICE_CATEGORY_DETAILS: '/service-categories',
  SERVICES: '/services',
  SERVICE_DETAILS: '/services',
  PUJA_TYPES: '/puja-types',
  PUJA_TYPE_DETAILS: '/puja-types',
  PUJAS: '/pujas',
  PUJA_DETAILS: '/pujas',
  SERVICEMEN: '/servicemen',
  BRAHMANS: '/brahmans',
  USER_LOGIN: '/user/login',
  SERVICEMAN_LOGIN: '/serviceman/login',
  BRAHMAN_LOGIN: '/brahman/login',
  LOGOUT: '/logout',
  USER_REGISTER: '/user/register',
  SERVICEMAN_REGISTER: '/serviceman/register',
  BRAHMAN_REGISTER: '/brahman/register',
} as const;

