export const API_ENDPOINTS = {
  HOME: '/home',
  SERVICE_CATEGORIES: '/service-categories',
  SERVICE_CATEGORY_DETAILS: '/service-categories',
  SERVICES: '/services',
  SERVICE_DETAILS: '/services',
  PUJA_TYPES: '/puja-types',
  PUJA_TYPE_DETAILS: '/puja-types',
  PUJAS: '/pujas',
  PUJA_DETAILS: '/pujas',
  SERVICEMEN: '/servicemen',
  BRAHMANS: '/brahmans',
  USER_LOGIN: '/user/login',
  SERVICEMAN_LOGIN: '/serviceman/login',
  BRAHMAN_LOGIN: '/brahman/login',
  LOGOUT: '/logout',
  USER_REGISTER: '/user/register',
  SERVICEMAN_REGISTER: '/serviceman/register',
  BRAHMAN_REGISTER: '/brahman/register',
  USER_PROFILE_UPDATE: '/user/profile/update',
  SERVICEMAN_PROFILE_UPDATE: '/serviceman/profile/update',
  BRAHMAN_PROFILE_UPDATE: '/brahman/profile/update',
  DELETE_ACCOUNT: '/user/delete-account',
  TERMS_AND_CONDITIONS: '/terms-and-conditions',
  PRIVACY_POLICY: '/privacy-policy',
  ABOUT_US: '/about-us',
  BOOKINGS: '/bookings',
  SERVICE_BOOKING: '/bookings/service',
  PUJA_BOOKING: '/bookings/puja',
} as const;

